<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Demande_FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Demande_FormationRepository extends EntityRepository
{
}
