<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NatureAbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatureAbsenceRepository extends EntityRepository
{
}
