<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
    
}
