<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Type_ContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_ContratRepository extends EntityRepository
{
}
